name: Playwright Tests execution
on:
  workflow_dispatch:
    inputs:
      build-environment:
        description: 'Target environment'
        required: false
        type: string
        default: dev

jobs:
  Automation-TestExecution:
    timeout-minutes: 60
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright test on staging environment
      run: npm run env:${{github.event.inputs.build-environment}}

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
